"""Éditeur ksf.env : schéma typé, validation, dry-run, diff, rollback.

Workflow d'écriture :
1. Valider chaque champ contre le schéma
2. Backup auto de l'ancien contenu → config_versions
3. Écriture atomique du nouveau fichier (write tmp, fsync, rename)
4. ksf.sh render --dry-run pour vérifier l'impact
5. Si OK, proposer le commit (modal diff dans l'UI) avec un token
   de binding preview/commit
6. Si commit validé (avec le bon token), ksf.sh render (sans --dry-run)
7. Si commit échoue, restore depuis la version de backup

Binding preview/commit : un token signé est généré à chaque preview
réussi. Le commit doit présenter ce token. Ça empêche un caller
malveillant (ou un browser compromis) de commit n'importe quel
contenu.
"""
import asyncio
import hashlib
import hmac
import os
import re
import json
import difflib
import logging
import secrets
import subprocess
import time

from app import config, db
from app.utils import utcnow_str as _utcnow

logger = logging.getLogger("ksf-web.config")

KSF_ENV_PATH = os.path.join(config.BASE_DIR, "config", "ksf.env")
# Secret utilisé pour signer les tokens preview/commit. Différent du
# CSRF secret (sécurité par compartimentation) mais dérivé de la même
# source pour la simplicité.
PREVIEW_SECRET = (config.CSRF_SECRET + ":config-editor").encode("utf-8")
PREVIEW_TOKEN_MAX_AGE = 300  # 5 minutes


def read_current() -> dict[str, str]:
    if not os.path.isfile(KSF_ENV_PATH):
        return {}
    out = {}
    with open(KSF_ENV_PATH) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            out[k.strip()] = v.strip().strip("\"'")
    return out


def _read_raw() -> str:
    if not os.path.isfile(KSF_ENV_PATH):
        return ""
    with open(KSF_ENV_PATH) as f:
        return f.read()


def _validate_value(field: dict, value: str) -> str | None:
    t = field["type"]
    v = (value or "").strip()
    if field.get("required") and not v:
        return f"{field['key']} est requis"
    if not v:
        return None
    if t == "bool":
        if v.lower() not in ("true", "false", "1", "0", "yes", "no"):
            return f"{field['key']}: booléen invalide (true/false)"
    elif t == "email":
        if not re.fullmatch(r"[^@\s]+@[^@\s]+\.[^@\s]+", v):
            return f"{field['key']}: email invalide"
    elif t == "domain":
        if not re.fullmatch(r"[a-zA-Z0-9]([a-zA-Z0-9\-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9\-]*[a-zA-Z0-9])?)*", v):
            return f"{field['key']}: domaine invalide"
    elif t == "int":
        if not v.lstrip("-").isdigit():
            return f"{field['key']}: entier invalide"
    return None


def validate(values: dict[str, str]) -> list[dict[str, str]]:
    errors = []
    for f in SCHEMA:
        v = values.get(f["key"], "")
        err = _validate_value(f, v)
        if err:
            errors.append({"key": f["key"], "error": err})
    return errors


def form_from_current() -> list[dict]:
    cur = read_current()
    out = []
    for f in SCHEMA:
        out.append({**f, "value": cur.get(f["key"], f.get("default", ""))})
    return out


def _serialize(values: dict[str, str]) -> str:
    """Sérialise les valeurs en format .env.

    - Rejette les valeurs contenant des newlines (corromprait le fichier)
    - Quote les valeurs avec espaces (sinon parse.sh échoue)
    """
    def _format_value(v: str) -> str:
        if "\n" in v or "\r" in v:
            raise ValueError("Les valeurs ne peuvent pas contenir de newline")
        if " " in v or "\t" in v or '"' in v or "'" in v:
            # Simple quote with double quotes, escape internal double quotes
            return f'"{v.replace(chr(34), chr(92) + chr(34))}"'
        return v

    lines = ["# KSF platform configuration", "# Generated by ksf-web\n"]
    for f in SCHEMA:
        v = (values.get(f["key"], "") or "").strip()
        if not v and "default" in f:
            v = f["default"]
        if v:
            lines.append(f'{f["key"]}={_format_value(v)}')
    others = []
    cur = read_current()
    schemed = {f["key"] for f in SCHEMA}
    for k, v in cur.items():
        if k in schemed:
            continue
        if k.startswith("#") or not v:
            continue
        others.append((k, v))
    if others:
        lines.append("\n# Variables personnalisées (non schématisées)")
        for k, v in others:
            lines.append(f"{k}={_format_value(v)}")
    return "\n".join(lines) + "\n"


def diff(current: str, proposed: str) -> str:
    """Retourne un diff unifié lisible."""
    diff_lines = list(difflib.unified_diff(
        current.splitlines(keepends=True),
        proposed.splitlines(keepends=True),
        fromfile="actuel", tofile="proposé", n=2,
    ))
    if not diff_lines:
        return "(aucun changement)"
    return "".join(diff_lines)


async def _save_version(content: str, actor: str, reason: str) -> int:
    async for conn in db.get_conn():
        cur = await conn.execute(
            "INSERT INTO config_versions (path, content, actor, reason, created_at) VALUES (?, ?, ?, ?, ?)",
            (KSF_ENV_PATH, content, actor, reason, _utcnow()),
        )
        await conn.commit()
        return cur.lastrowid


async def list_versions(limit: int = 20) -> list[dict]:
    """Liste les versions SANS le content (lazy-load via get_version)."""
    async for conn in db.get_conn():
        cur = await conn.execute(
            "SELECT id, actor, reason, created_at, length(content) as size "
            "FROM config_versions ORDER BY id DESC LIMIT ?",
            (limit,),
        )
        rows = await cur.fetchall()
        await cur.close()
        return [dict(r) for r in rows]


async def get_version(version_id: int) -> dict | None:
    async for conn in db.get_conn():
        cur = await conn.execute(
            "SELECT id, content, actor, reason, created_at, length(content) as size "
            "FROM config_versions WHERE id=?",
            (version_id,),
        )
        row = await cur.fetchone()
        await cur.close()
        return dict(row) if row else None


def _run_render(args: list[str], timeout: int) -> tuple[bool, str]:
    try:
        result = subprocess.run(
            [config.REPO_DIR + "/ksf.sh"] + args,
            capture_output=True, text=True, timeout=timeout,
            cwd=config.REPO_DIR,
            env={**os.environ, "KSF_BASE_DIR": config.BASE_DIR, "HOME": "/home/appuser"},
        )
        return result.returncode == 0, (result.stdout + result.stderr).strip()
    except subprocess.TimeoutExpired:
        return False, f"Le render a dépassé le timeout ({timeout}s)."
    except FileNotFoundError:
        return False, f"ksf.sh introuvable : {config.REPO_DIR}/ksf.sh"
    except Exception as e:
        return False, f"Erreur render : {e}"


async def dryrun_render() -> tuple[bool, str]:
    """Lance ksf.sh render --dry-run (async, non bloquant)."""
    return await asyncio.to_thread(_run_render, ["render", "--dry-run"], 60)


async def commit_render() -> tuple[bool, str]:
    """Lance ksf.sh render (async, non bloquant)."""
    return await asyncio.to_thread(_run_render, ["render"], 120)


def write_atomic(content: str) -> bool:
    try:
        os.makedirs(os.path.dirname(KSF_ENV_PATH), exist_ok=True)
        tmp = KSF_ENV_PATH + ".tmp"
        with open(tmp, "w") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, KSF_ENV_PATH)
        os.chmod(KSF_ENV_PATH, 0o600)
        return True
    except OSError as e:
        logger.exception("Échec écriture atomique de ksf.env")
        return False


async def preview(values: dict[str, str]) -> dict:
    errors = validate(values)
    if errors:
        return {"ok": False, "errors": errors}
    proposed = _serialize(values)
    current = _read_raw()
    diff_text = diff(current, proposed)
    # Génère un token signé qui lie le caller à CE contenu proposé
    # pendant PREVIEW_TOKEN_MAX_AGE secondes. Le commit doit présenter
    # exactement ce token avec exactement le même contenu.
    token = _sign_preview_token(proposed)
    return {"ok": True, "diff": diff_text, "proposed": proposed, "current": current, "token": token}


def _sign_preview_token(proposed_content: str) -> str:
    """Génère un token signé pour lier preview et commit."""
    nonce = secrets.token_urlsafe(16)
    expires = int(time.time()) + PREVIEW_TOKEN_MAX_AGE
    payload = f"{nonce}:{expires}:{len(proposed_content)}"
    sig = hmac.new(PREVIEW_SECRET, payload.encode("utf-8"), hashlib.sha256).hexdigest()[:32]
    return f"{payload}:{sig}"


def _verify_preview_token(token: str, proposed_content: str) -> bool:
    """Vérifie que le token a été émis pour CE contenu et qu'il n'a pas expiré."""
    try:
        nonce, expires_str, length_str, sig = token.rsplit(":", 3)
        expires = int(expires_str)
        if expires < int(time.time()):
            return False
        if int(length_str) != len(proposed_content):
            return False
        payload = f"{nonce}:{expires}:{length_str}"
        expected_sig = hmac.new(PREVIEW_SECRET, payload.encode("utf-8"), hashlib.sha256).hexdigest()[:32]
        return hmac.compare_digest(sig, expected_sig)
    except (ValueError, AttributeError):
        return False


async def commit(proposed_content: str, token: str, actor: str = "admin") -> dict:
    """Workflow complet de commit : backup → write → dry-run → render.

    Vérifie que le token lie bien ce contenu (preview/commit binding).
    En cas d'échec du dry-run ou du commit réel, restore automatique
    depuis le backup créé en début de workflow.
    """
    if not _verify_preview_token(token, proposed_content):
        return {
            "ok": False, "stage": "token",
            "error": "Token preview invalide ou expiré. Relancez la prévisualisation."
        }

    current = _read_raw()
    if proposed_content == current:
        return {"ok": True, "stage": "noop", "message": "Aucun changement."}

    # Backup de l'état actuel avant écriture (pour rollback)
    await _save_version(current, actor, "before edit")

    # Écriture atomique du nouveau contenu
    if not write_atomic(proposed_content):
        return {
            "ok": False, "stage": "write",
            "error": "Écriture impossible. Permissions du fichier host ?",
        }

    # Dry-run : vérifie que ksf.sh render ne va pas casser la plateforme
    ok, output = await dryrun_render()
    if not ok:
        rollback_ok = write_atomic(current)
        return {
            "ok": False, "stage": "dryrun", "output": output,
            "rolled_back": rollback_ok,
            "error": "Dry-run a échoué. Fichier restauré.",
        }

    # Commit réel : applique ksf.sh render (Traefik, OAuth2, etc.)
    ok, output = await commit_render()
    if not ok:
        rollback_ok = write_atomic(current)
        return {
            "ok": False, "stage": "commit", "output": output,
            "rolled_back": rollback_ok,
            "error": "Commit a échoué. Fichier restauré.",
        }

    # Sauvegarde post-commit pour historique
    await _save_version(proposed_content, actor, "after commit")
    return {"ok": True, "stage": "commit-ok", "output": output}
