"""Éditeur ksf.env : schéma typé, validation, dry-run, diff, rollback.

Workflow d'écriture :
1. Valider chaque champ contre le schéma
2. Backup auto de l'ancien contenu → config_versions
3. Écriture atomique du nouveau fichier (write tmp, fsync, rename)
4. ksf.sh render --dry-run pour vérifier l'impact
5. Si OK, proposer le commit (modal diff dans l'UI)
6. Si commit validé, ksf.sh render (sans --dry-run)
7. Si commit échoue, restore depuis la version de backup
"""
import asyncio
import os
import re
import json
import difflib
import logging
import subprocess
from datetime import datetime, timezone

from app import config, db

logger = logging.getLogger("ksf-web.config")

KSF_ENV_PATH = os.path.join(config.BASE_DIR, "config", "ksf.env")

SCHEMA: list[dict] = [
    {"key": "DOMAIN", "type": "domain", "required": True, "section": "core",
     "help": "Domaine principal de la plateforme (ex: example.com)."},
    {"key": "ACME_EMAIL", "type": "email", "required": False, "section": "core",
     "help": "Email pour Let's Encrypt."},
    {"key": "WITH_TRAEFIK", "type": "bool", "default": "true", "section": "core"},
    {"key": "WITH_OAUTH2", "type": "bool", "default": "true", "section": "core"},
    {"key": "OAUTH_CLIENT_ID", "type": "string", "section": "oauth2", "secret": True},
    {"key": "OAUTH_CLIENT_SECRET", "type": "string", "section": "oauth2", "secret": True},
    {"key": "OAUTH_GITHUB_USER", "type": "string", "section": "oauth2"},
    {"key": "WITH_CROWDSEC", "type": "bool", "default": "false", "section": "security"},
    {"key": "CROWDSEC_APPSEC_ENABLED", "type": "bool", "default": "false", "section": "security"},
    {"key": "TRAEFIK_TRUSTED_IPS", "type": "string", "section": "security", "advanced": True,
     "help": "CIDR séparés par virgule (ex: 173.245.48.0/20,...)."},
    {"key": "TZ_VALUE", "type": "string", "default": "Europe/Paris", "section": "system"},
    {"key": "BACKUP_KEEP", "type": "int", "default": "5", "section": "system"},
]


def _utcnow() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def read_current() -> dict[str, str]:
    if not os.path.isfile(KSF_ENV_PATH):
        return {}
    out = {}
    with open(KSF_ENV_PATH) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, _, v = line.partition("=")
            out[k.strip()] = v.strip().strip("\"'")
    return out


def _read_raw() -> str:
    if not os.path.isfile(KSF_ENV_PATH):
        return ""
    with open(KSF_ENV_PATH) as f:
        return f.read()


def _validate_value(field: dict, value: str) -> str | None:
    t = field["type"]
    v = (value or "").strip()
    if field.get("required") and not v:
        return f"{field['key']} est requis"
    if not v:
        return None
    if t == "bool":
        if v.lower() not in ("true", "false", "1", "0", "yes", "no"):
            return f"{field['key']}: booléen invalide (true/false)"
    elif t == "email":
        if not re.fullmatch(r"[^@\s]+@[^@\s]+\.[^@\s]+", v):
            return f"{field['key']}: email invalide"
    elif t == "domain":
        if not re.fullmatch(r"[a-zA-Z0-9]([a-zA-Z0-9\-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9\-]*[a-zA-Z0-9])?)*", v):
            return f"{field['key']}: domaine invalide"
    elif t == "int":
        if not v.lstrip("-").isdigit():
            return f"{field['key']}: entier invalide"
    return None


def validate(values: dict[str, str]) -> list[dict[str, str]]:
    errors = []
    for f in SCHEMA:
        v = values.get(f["key"], "")
        err = _validate_value(f, v)
        if err:
            errors.append({"key": f["key"], "error": err})
    return errors


def form_from_current() -> list[dict]:
    cur = read_current()
    out = []
    for f in SCHEMA:
        out.append({**f, "value": cur.get(f["key"], f.get("default", ""))})
    return out


def _serialize(values: dict[str, str]) -> str:
    lines = ["# KSF platform configuration", "# Generated by ksf-web\n"]
    for f in SCHEMA:
        v = (values.get(f["key"], "") or "").strip()
        if not v and "default" in f:
            v = f["default"]
        if v:
            lines.append(f'{f["key"]}={v}')
    others = []
    cur = read_current()
    schemed = {f["key"] for f in SCHEMA}
    for k, v in cur.items():
        if k in schemed:
            continue
        if k.startswith("#") or not v:
            continue
        others.append((k, v))
    if others:
        lines.append("\n# Variables personnalisées (non schématisées)")
        for k, v in others:
            lines.append(f"{k}={v}")
    return "\n".join(lines) + "\n"


def diff(current: str, proposed: str) -> str:
    """Retourne un diff unifié lisible."""
    diff_lines = list(difflib.unified_diff(
        current.splitlines(keepends=True),
        proposed.splitlines(keepends=True),
        fromfile="actuel", tofile="proposé", n=2,
    ))
    if not diff_lines:
        return "(aucun changement)"
    return "".join(diff_lines)


async def _save_version(content: str, actor: str, reason: str) -> int:
    async for conn in db.get_conn():
        cur = await conn.execute(
            "INSERT INTO config_versions (path, content, actor, reason, created_at) VALUES (?, ?, ?, ?, ?)",
            (KSF_ENV_PATH, content, actor, reason, _utcnow()),
        )
        await conn.commit()
        return cur.lastrowid


async def list_versions(limit: int = 20) -> list[dict]:
    async for conn in db.get_conn():
        cur = await conn.execute(
            "SELECT id, content, actor, reason, created_at, length(content) as size "
            "FROM config_versions ORDER BY id DESC LIMIT ?",
            (limit,),
        )
        rows = await cur.fetchall()
        await cur.close()
        return [dict(r) for r in rows]


async def get_version(version_id: int) -> dict | None:
    async for conn in db.get_conn():
        cur = await conn.execute(
            "SELECT id, content, actor, reason, created_at, length(content) as size "
            "FROM config_versions WHERE id=?",
            (version_id,),
        )
        row = await cur.fetchone()
        await cur.close()
        return dict(row) if row else None


def _run_render(args: list[str], timeout: int) -> tuple[bool, str]:
    try:
        result = subprocess.run(
            [config.REPO_DIR + "/ksf.sh"] + args,
            capture_output=True, text=True, timeout=timeout,
            cwd=config.REPO_DIR, env={**os.environ, "KSF_BASE_DIR": config.BASE_DIR},
        )
        return result.returncode == 0, (result.stdout + result.stderr).strip()
    except subprocess.TimeoutExpired:
        return False, f"Le render a dépassé le timeout ({timeout}s)."
    except FileNotFoundError:
        return False, f"ksf.sh introuvable : {config.REPO_DIR}/ksf.sh"
    except Exception as e:
        return False, f"Erreur render : {e}"


async def dryrun_render() -> tuple[bool, str]:
    """Lance ksf.sh render --dry-run (async, non bloquant)."""
    return await asyncio.to_thread(_run_render, ["render", "--dry-run"], 60)


async def commit_render() -> tuple[bool, str]:
    """Lance ksf.sh render (async, non bloquant)."""
    return await asyncio.to_thread(_run_render, ["render"], 120)


def write_atomic(content: str) -> bool:
    try:
        os.makedirs(os.path.dirname(KSF_ENV_PATH), exist_ok=True)
        tmp = KSF_ENV_PATH + ".tmp"
        with open(tmp, "w") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, KSF_ENV_PATH)
        os.chmod(KSF_ENV_PATH, 0o600)
        return True
    except OSError as e:
        logger.exception("Échec écriture atomique de ksf.env")
        return False


async def preview(values: dict[str, str]) -> dict:
    errors = validate(values)
    if errors:
        return {"ok": False, "errors": errors}
    proposed = _serialize(values)
    current = _read_raw()
    diff_text = diff(current, proposed)
    return {"ok": True, "diff": diff_text, "proposed": proposed, "current": current}


async def apply(values: dict[str, str], actor: str = "admin") -> dict:
    """Workflow complet : validate → backup → write → dry-run → commit/restore."""
    errors = validate(values)
    if errors:
        return {"ok": False, "stage": "validate", "errors": errors}

    proposed = _serialize(values)
    current = _read_raw()
    if proposed == current:
        return {"ok": True, "stage": "noop", "message": "Aucun changement."}

    await _save_version(current, actor, "before edit")
    if not write_atomic(proposed):
        return {"ok": False, "stage": "write", "errors": [{"key": "_", "error": "Écriture impossible."}]}

    ok, output = await dryrun_render()
    if not ok:
        rollback_ok = write_atomic(current)
        return {
            "ok": False, "stage": "dryrun", "output": output,
            "rolled_back": rollback_ok,
            "errors": [{"key": "_", "error": "Dry-run a échoué. Fichier restauré."}],
        }

    return {"ok": True, "stage": "dryrun-ok", "output": output, "proposed": proposed, "current": current}


async def commit(proposed_content: str, actor: str = "admin") -> dict:
    """Commit final après dry-run OK. Lance ksf.sh render."""
    ok, output = await commit_render()
    if not ok:
        return {"ok": False, "stage": "commit", "output": output}
    await _save_version(proposed_content, actor, "after commit")
    return {"ok": True, "stage": "commit-ok", "output": output}
